---
- name: Install the latest version of  python3, python3-dev, python3-pip ans setup backendserver
  hosts: backend
  become: true
  connection: ssh
  tasks:
  - name: Install python3
    apt:
          name: python3
          state: latest
  - name: Install python3-dev
    apt:
          update_cache: yes
          name: python3-dev
          state: latest
  - name: Install python3-pip
    apt:
          name: python3-pip
          state: latest
  - name: Install virtual environment
    command: pip3 install virtualenv

  - name: Installing gcc packages on server
    apt:
         name: "gcc"
         state: latest

  - name: Install mysql dev packages on server
    apt:
         name: ["libmysqlclient-dev"]
         state: latest

  - name: copy file from one folder to other on remote server
    become: yes
    copy:
       src: /home/ubuntu/new_chatapp
       dest: /home/ubuntu/

  - name: Installing mysql packages on server
    pip:
         name: ["mysqlclient"]
         state: present
         executable: pip3

  - name: create virtual environment env
    command:
            cmd: virtualenv /home/ubuntu/new_chatapp/env -p python3
            creates: "/home/ubuntu/new_chatapp/env"
  - name: Install requirements
    pip:
            requirements: /home/ubuntu/new_chatapp/requirements.txt
            virtualenv: /home/ubuntu/new_chatapp/env
            state: present


  - name: decrypting django mysql on server
    pip:
        name: "bcrypt"
        state: present
        executable: pip3

  - name: django installation
    pip:
        name: "django"
        state: present
        version: 2.2.4

  - name: copy gunicorn.service file form server to backEnd node
    copy:
            src: /home/ubuntu/gunicorn.service
            dest: /etc/systemd/system/
  - name: start gunicorn
    become: true
    command: systemctl daemon-reload

  - name: enable gunicorn
    become: true
    command: systemctl enable gunicorn

  - name: start gunicorn
    become: true
    command: systemctl start gunicorn
